In [16]:
import numpy as np
import pandas as pd
s=pd.Series((1,2,3,4,5,6))
print (s)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [3]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [4]:
s.values

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [5]:
pd.read_csv

<function pandas.io.parsers._make_parser_function.<locals>.parser_f(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, skipfooter=0, doublequote=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)>

In [5]:
s1=pd.Series((np.random.rand(5)),('a','b','c','d','e'))
s1

a    0.985631
b    0.426175
c    0.283525
d    0.075673
e    0.852695
dtype: float64

In [6]:
s1.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [7]:
Test=pd.read_csv("D:\Data Science\Shalini Basics 1\Test1.csv")
Test.columns

Index(['A', 'B'], dtype='object')

In [8]:
Test.columns[0:1]

Index(['A'], dtype='object')

In [9]:
Test.dtypes

A     int64
B    object
dtype: object

In [10]:
Test["A"].dtypes

dtype('int64')

In [11]:
s1[3]==s1['d']

True

In [12]:
s1[s1>0]

a    0.985631
b    0.426175
c    0.283525
d    0.075673
e    0.852695
dtype: float64

In [13]:
s1*2

a    1.971262
b    0.852351
c    0.567049
d    0.151346
e    1.705390
dtype: float64

In [14]:
np.exp(s1)

a    2.679502
b    1.531389
c    1.327802
d    1.078610
e    2.345960
dtype: float64

In [21]:
import pandas as pd
dict_1 = {'foo' : 100, 'bar' : 200, 'baz' : 300}
ser_3 = pd.Series(dict_1)
ser_3

foo    100
bar    200
baz    300
dtype: int64

In [23]:
index = ['foo', 'bar', 'baz', 'qux']
ser_4 = pd.Series(dict_1, index=index)
ser_4

foo    100.0
bar    200.0
baz    300.0
qux      NaN
dtype: float64

In [24]:
ser_4.isnull()

foo    False
bar    False
baz    False
qux     True
dtype: bool

In [25]:
pd.isnull(ser_4)

foo    False
bar    False
baz    False
qux     True
dtype: bool

In [26]:
ser_3+ser_4

bar    400.0
baz    600.0
foo    200.0
qux      NaN
dtype: float64

In [32]:
data_1={"State":["VA","VA","VA","MD","MD"],
        "Year":[2012,2013,2014,2015,2016],
        "Pop":[5.0,5.1,5.2,4.0,4.1]}
df_1=pd.DataFrame(data_1)
df_1

State  Year  Pop
0    VA  2012  5.0
1    VA  2013  5.1
2    VA  2014  5.2
3    MD  2015  4.0
4    MD  2016  4.1

In [37]:
df_2=pd.DataFrame(data_1,columns=['Year','State','Pop'])
df_2

Year State  Pop
0  2012    VA  5.0
1  2013    VA  5.1
2  2014    VA  5.2
3  2015    MD  4.0
4  2016    MD  4.1

In [39]:
df_3=pd.DataFrame(data_1,columns=['Year','State','Pop','Unempl'])
df_3

Year State  Pop Unempl
0  2012    VA  5.0    NaN
1  2013    VA  5.1    NaN
2  2014    VA  5.2    NaN
3  2015    MD  4.0    NaN
4  2016    MD  4.1    NaN

In [40]:
df_3['State']

0    VA
1    VA
2    VA
3    MD
4    MD
Name: State, dtype: object

In [42]:
df_3.Year

0    2012
1    2013
2    2014
3    2015
4    2016
Name: Year, dtype: int64

In [44]:
df_3.iloc[0]

Year      2012
State       VA
Pop          5
Unempl     NaN
Name: 0, dtype: object

In [46]:
df_3['Unempl']=np.arange(5)
df_3

Year State  Pop  Unempl
0  2012    VA  5.0       0
1  2013    VA  5.1       1
2  2014    VA  5.2       2
3  2015    MD  4.0       3
4  2016    MD  4.1       4

In [47]:
unempl=pd.Series([6.0,6.1,6.1],[2,3,4])
df_3['Unempl']=unempl
df_3

Year State  Pop  Unempl
0  2012    VA  5.0     NaN
1  2013    VA  5.1     NaN
2  2014    VA  5.2     6.0
3  2015    MD  4.0     6.1
4  2016    MD  4.1     6.1

In [48]:
df_3['State_dup']=df_3['State']
df_3

Year State  Pop  Unempl State_dup
0  2012    VA  5.0     NaN        VA
1  2013    VA  5.1     NaN        VA
2  2014    VA  5.2     6.0        VA
3  2015    MD  4.0     6.1        MD
4  2016    MD  4.1     6.1        MD

In [49]:
del df_3['State_dup']
df_3

Year State  Pop  Unempl
0  2012    VA  5.0     NaN
1  2013    VA  5.1     NaN
2  2014    VA  5.2     6.0
3  2015    MD  4.0     6.1
4  2016    MD  4.1     6.1

In [50]:
pop={'VA':{2013:5.1,2014:5.2},
     'MD':{2014:4.0,2015:4.1}}
df_4=pd.DataFrame(pop)
df_4

VA   MD
2013  5.1  NaN
2014  5.2  4.0
2015  NaN  4.1

In [51]:
data_2={'VA':df_4['VA'][1:],
        'MD':df_4['MD'][2:]}
df_5=pd.DataFrame(data_2)
df_5

VA   MD
2014  5.2  NaN
2015  NaN  4.1

In [52]:
df_5.values

array([[5.2, nan],
       [nan, 4.1]])

In [53]:
df_3.values

array([[2012, 'VA', 5.0, nan],
       [2013, 'VA', 5.1, nan],
       [2014, 'VA', 5.2, 6.0],
       [2015, 'MD', 4.0, 6.1],
       [2016, 'MD', 4.1, 6.1]], dtype=object)

In [54]:
df_3

Year State  Pop  Unempl
0  2012    VA  5.0     NaN
1  2013    VA  5.1     NaN
2  2014    VA  5.2     6.0
3  2015    MD  4.0     6.1
4  2016    MD  4.1     6.1

In [56]:
df_3.reindex(list(reversed(range(0,6))))

Year State  Pop  Unempl
5     NaN   NaN  NaN     NaN
4  2016.0    MD  4.1     6.1
3  2015.0    MD  4.0     6.1
2  2014.0    VA  5.2     6.0
1  2013.0    VA  5.1     NaN
0  2012.0    VA  5.0     NaN

In [57]:
df_3.reindex(range(6,0),fill_value=0)

Empty DataFrame
Columns: [Year, State, Pop, Unempl]
Index: []

In [7]:
import pandas as pd
import numpy as np
dates=pd.date_range('20120101',periods=6)
dates
df1=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df1

A         B         C         D
2012-01-01 -0.390320 -0.737513  1.889469  0.236309
2012-01-02 -1.151971  0.582264  1.429477  0.254380
2012-01-03  1.141748 -0.602415  0.016329  0.400066
2012-01-04 -1.368233 -0.119110  0.112010 -0.339443
2012-01-05 -1.383935  0.790892  1.002089 -0.910213
2012-01-06 -0.291385  0.922662 -0.223403  1.351316

In [10]:
df2 = pd.DataFrame({ 'A' : 1.,
   ....:                      'B' : pd.Timestamp('20130102'),
   ....:                      'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
   ....:                      'D' : np.array([3] * 4,dtype='int32'),
   ....:                      'E' : pd.Categorical(["test","train","test","train"]),
   ....:                      'F' : 'foo' })
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [15]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [18]:
df1.head()

A         B         C         D
2012-01-01 -0.390320 -0.737513  1.889469  0.236309
2012-01-02 -1.151971  0.582264  1.429477  0.254380
2012-01-03  1.141748 -0.602415  0.016329  0.400066
2012-01-04 -1.368233 -0.119110  0.112010 -0.339443
2012-01-05 -1.383935  0.790892  1.002089 -0.910213

In [19]:
df1.tail(3)

A         B         C         D
2012-01-04 -1.368233 -0.119110  0.112010 -0.339443
2012-01-05 -1.383935  0.790892  1.002089 -0.910213
2012-01-06 -0.291385  0.922662 -0.223403  1.351316

In [20]:
df1.index

DatetimeIndex(['2012-01-01', '2012-01-02', '2012-01-03', '2012-01-04',
               '2012-01-05', '2012-01-06'],
              dtype='datetime64[ns]', freq='D')

In [21]:
df1.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [22]:
df1.values

array([[-0.39031987, -0.73751294,  1.88946856,  0.23630909],
       [-1.15197145,  0.58226375,  1.42947702,  0.25437977],
       [ 1.14174832, -0.60241486,  0.01632895,  0.40006579],
       [-1.36823282, -0.11910972,  0.11201032, -0.33944278],
       [-1.38393517,  0.79089164,  1.00208877, -0.91021279],
       [-0.29138459,  0.92266174, -0.2234031 ,  1.35131582]])

In [24]:
df1.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.574016  0.139463  0.704328  0.165402
std    0.967290  0.723901  0.860689  0.759766
min   -1.383935 -0.737513 -0.223403 -0.910213
25%   -1.314167 -0.481589  0.040249 -0.195505
50%   -0.771146  0.231577  0.557050  0.245344
75%   -0.316118  0.738735  1.322630  0.363644
max    1.141748  0.922662  1.889469  1.351316

In [25]:
df1.T

2012-01-01  2012-01-02  2012-01-03  2012-01-04  2012-01-05  2012-01-06
A   -0.390320   -1.151971    1.141748   -1.368233   -1.383935   -0.291385
B   -0.737513    0.582264   -0.602415   -0.119110    0.790892    0.922662
C    1.889469    1.429477    0.016329    0.112010    1.002089   -0.223403
D    0.236309    0.254380    0.400066   -0.339443   -0.910213    1.351316

In [26]:
df1.sort_index(axis=1,ascending=False)

D         C         B         A
2012-01-01  0.236309  1.889469 -0.737513 -0.390320
2012-01-02  0.254380  1.429477  0.582264 -1.151971
2012-01-03  0.400066  0.016329 -0.602415  1.141748
2012-01-04 -0.339443  0.112010 -0.119110 -1.368233
2012-01-05 -0.910213  1.002089  0.790892 -1.383935
2012-01-06  1.351316 -0.223403  0.922662 -0.291385

In [28]:
df1.sort_values(by='B')

A         B         C         D
2012-01-01 -0.390320 -0.737513  1.889469  0.236309
2012-01-03  1.141748 -0.602415  0.016329  0.400066
2012-01-04 -1.368233 -0.119110  0.112010 -0.339443
2012-01-02 -1.151971  0.582264  1.429477  0.254380
2012-01-05 -1.383935  0.790892  1.002089 -0.910213
2012-01-06 -0.291385  0.922662 -0.223403  1.351316

In [47]:
import numpy as np
import pandas as pd

#alpha=pd.Series(['a','b','d','A','B','D','e','F','G','K'])
#alpha_upper=alpha.isupper()
l=[]
U=[]
def getUpper(alpha1):
    for i in alpha1:
        if(i.isupper()):
            U.append(i)
        else:
            l.append(i)
    if len(U)>len(l):
        return U
    else:
        return l
#    alpha_upper=a.isupper(alpha)
alpha=['a','b','d','A','B','D','e','F','G','K']
getUpper(alpha)

['A', 'B', 'D', 'F', 'G', 'K']

In [8]:
alpha=['a','b','d','A','B','D','e','F','G','K']
b=[i for i in alpha if i==i.upper()]
b

['A', 'B', 'D', 'F', 'G', 'K']

In [43]:
alpha=['a','b','d','A','B','D','e','F','G','K']
#sum(map(alpha.islower))
a=reduce(lambda x:x.isupper(),alpha))
alpha_upper=list(filter(lambda x:x.isupper(),alpha))
alpha_upper

['A', 'B', 'D', 'F', 'G', 'K']

In [6]:
def string_reverse(s1):
    s=''
    index=len(s1)
    while index>0:
        s+=s1[index-1]
        index=index-1
    return s
def list_reverse(l1):
    l2=[]
    for i in l1:
        s2=''
        s2=string_reverse(i)
        l2.append(s2)
    return l2
fruits=['applE','Mango','Strawberry','orangE']
list_reverse(fruits)

['Elppa', 'ognaM', 'yrrebwartS', 'Egnaro']

In [50]:
fruits=['applE','Mango','Strawberry','orangE']
n=list(filter(lambda x:(x[0].isupper() and x[-1].islower()),fruits))
#alpha_upper=list(filter(lambda x:x.isupper(),alpha))
n

['Mango', 'Strawberry']

In [10]:
l=[1,2,5,6,7,8,10]
l1=list(map(lambda x:(x*5+10),l))
l1

[15, 20, 35, 40, 45, 50, 60]

In [12]:
def getmode(l):
    cnt=0
    for i in l:
        if l.count(i)>cnt:
            mode_value=i
            mode_count=l.count(i)
        cnt=l.count(i)
    print(mode_value,mode_count)
c=[1,2,1,2,2,2,1,1,2,2,2,1,5]
getmode(c)


2 7


In [6]:
x = ['ab', 'cd’] 
print(len(list(map(list, x))))

Object `upper` not found.


In [6]:
# To Find a number is Prime or not
import numpy as np
def chkprime(n):
    if n>1:
        for i in range(2,int(np.sqrt(n))):
            if (n%i==0):
                print(n,' is not a prime number')
                print(i,' times ',n//i,' is ',n)
                break
            else:
                print(n,' is a prime number')
    elif n==1:
        print('1 is a prime number')
    else:
        print(n,' is not a prime number')
chkprime(111123)

111123  is a prime number
111123  is not a prime number
3  times  37041  is  111123
