In [1]:
import numpy as np

a=np.array([1,2,3])
print (a)

[1 2 3]


In [2]:
print (type(a))
print (a.shape)
print (a[1])

<class 'numpy.ndarray'>
(3,)
2


In [36]:
a[0]=3
print (a)

[3 2 3]


In [37]:
a2d=np.array([[1,2,3],[4,5,6]])
print (a2d)
print (a2d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [38]:
print(type(a2d))
a2d.dtype

<class 'numpy.ndarray'>


dtype('int32')

In [39]:
a2d[1,1]

5

In [41]:
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],np.float32)
print (b)
b=b.reshape(4,4)
print (b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [42]:
print(type(b))
b.dtype

<class 'numpy.ndarray'>


dtype('float32')

In [43]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [48]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [51]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
ide=np.diag([1,2,3,4,5])
print(ide)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [57]:
b

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]], dtype=float32)

In [3]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10],[40]])
print (a)
print (b)

[[1 2 3]
 [4 5 6]]
[[10]
 [40]]


In [4]:
np.add(a,b)

array([[11, 12, 13],
       [44, 45, 46]])

In [12]:
import csv
with open("alcoholquality-red.csv",'r') as f:
    alcohols=list(csv.reader(f,delimiter=";"))
print(alcohols[:3])

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]
